### ISSUE TITLE
CheckoutService 1.0 meta ticket

### ISSUE THREAD

**Issue by cburgdorf** [sofa/sofa-checkout-service#7]
- [ ] integrate new checkoutService in `sofa-1.0` branch of sofa-app
- [ ] implement most minimal flow
- [ ] implement missing methods (pick things from Ingos checkoutService 1.0 branch)

API Endpoint: "http://apimagento.datacenter.couchcommerce.com/v1/stores/1"
